//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EczaneOtomasyonEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calisanlar()
        {
            this.ilac_satis = new HashSet<ilac_satis>();
        }
    
        public int calisan_id { get; set; }
        public int rol_id { get; set; }
        public string calisan_adi { get; set; }
        public string calisan_soyadi { get; set; }
        public string TC { get; set; }
        public string kullanici_adi { get; set; }
        public string parola { get; set; }
    
        public virtual roller roller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ilac_satis> ilac_satis { get; set; }
    }
}
