//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EczaneOtomasyonEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilaclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ilaclar()
        {
            this.ilac_satis = new HashSet<ilac_satis>();
        }
    
        public int ilac_id { get; set; }
        public string ilac_ismi { get; set; }
        public int tur_id { get; set; }
        public System.DateTime uretim_tarihi { get; set; }
        public System.DateTime tuketim_tarihi { get; set; }
        public double fiyat { get; set; }
        public int stok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ilac_satis> ilac_satis { get; set; }
        public virtual ilac_turleri ilac_turleri { get; set; }
    }
}
