//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EczaneOtomasyonEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilac_satis
    {
        public int satis_id { get; set; }
        public int musteri_id { get; set; }
        public int ilac_id { get; set; }
        public int personel_id { get; set; }
        public double satis_fiyati { get; set; }
        public System.DateTime satis_tarihi { get; set; }
        public int adet { get; set; }
    
        public virtual calisanlar calisanlar { get; set; }
        public virtual ilaclar ilaclar { get; set; }
        public virtual musteri musteri { get; set; }
    }
}
